name: CMD-twist
channels:
    - conda-forge
    - bioconda
    - defaults

dependencies:
    - conda-forge:python=3.9.2
    - bioconda::picard=2.25.2
    - bioconda::bwa=0.7.17
    - bioconda::vcflib=1.0.2
    - bioconda::snpsift=4.3
    - bioconda::samtools=1.12
    - bioconda::tabix=0.2.6
    - bioconda::freebayes=1.3.5
    - bioconda::pindel=0.2.5b9
    - bioconda::vardict-java=1.8.2
    - bioconda::bedtools=2.30.0
    - bioconda::vcftools=0.1.16
    - bioconda::perl-vcftools-vcf=0.1.16
    - bioconda::vt=2015.11.10
    - bioconda::perl-app-cpanminus==1.7044
    - bioconda::bcftools==1.12
    - bioconda::delly=0.8.7
    - bioconda::varlociraptor=3.0.0
    - conda-forge::jq==1.6